spring.application.name=convocatorias
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bdConvocatorias;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=convocatorias
spring.jpa.show-sql=true
app.jwt.secret=ClaveSecretaUSCOConvocatorias2026CambiarEnProduccionPorFavor
app.jwt.expiration-ms=86400000